var courses = [
    {
        name: 'Complete Course Web Development',
        description: 'Become a full-stack web developer with just one course. HTML, CSS, Javascript, Node, React, MongoDB and more!',
        mentor: 'Jhankar Mahbub',
        hours: '80 hours',
        lectures: '570',
        price: 70.99,
        img: 'https://i.ytimg.com/vi/p0F-k3C1zns/maxresdefault.jpg',
    },
    {
        name: 'Combo : Graphic & Web Design',
        description: 'Illustrator,Photoshop,XD,FREELANCING,HTML,WORDPRESS',
        mentor: 'Md.Jasim',
        hours: '65 hours',
        lectures: '45',
        price: 49.99,
        img: 'https://static-01.daraz.com.bd/p/059e4254c775c3ae9db15d55a6b4eb41.png_340x340q80.jpg_.webp',
    },
    {
        name: 'The Complete 2020 Web Development Bootcamp',
        description: 'Become a full-stack web developer with just one course. HTML, CSS, Javascript, Node, React, MongoDB and more!',
        mentor: 'Dr. Angela Yu',
        hours: '54 hours',
        lectures: '459',
        price: 149.99,
        img: 'https://img-a.udemycdn.com/course/240x135/1565838_e54e_11.jpg',
    },

    {
        name: 'Full Stack Web Development',
        description: 'HTML, CSS,BOOTSTRAP,WORDPRESS,PHP-MYSQL,FREELANCING',
        mentor: 'Omar Faruk',
        hours: '54 hours',
        lectures: '35',
        price: 64.99,
        img: 'https://miro.medium.com/max/1600/1*j18U6uvAg-ta2XBvDKNQlA.jpeg',
    },
    {
        name: 'React - The Complete Guide (incl Hooks, React Router, Redux)',
        description: 'Dive in and learn React.js from scratch! Learn Reactjs, Hooks, Redux, React Routing, Animations, Next.js and way more!',
        mentor: 'Maximilian Schwarzmüller',
        hours: '40 hours',
        lectures: '490',
        price: 134.99,
        img: 'https://img-a.udemycdn.com/course/240x135/1362070_b9a1_2.jpg',
    },
    {
        name: 'Full-Stack React with GraphQL and Apollo Boost',
        description: 'Build and deploy a full-stack React and GraphQL app from scratch with Apollo Boost, Express, and MongoDB',
        mentor: 'Reed Barger',
        hours: '6 hours',
        lectures: '76',
        price: 34.99,
        img: 'https://img-a.udemycdn.com/course/240x135/1715894_4509_6.jpg',
    },
    {
        name: 'Complete Python Mastery',
        description: 'Python is the most popular coding language in the world. Dont fall behind! Get all the skills you need in one course.',
        mentor: 'Maximilian Schwarzmüller',
        hours: '12 hours',
        lectures: '200',
        price: 45.99,
        img: 'https://img-a.udemycdn.com/course/750x422/2473048_8255_4.jpg',
    },
    {
        name: 'Ultimate Photoshop Training: From Beginner to Pro',
        description: 'Master Photoshop CC 2020 without any previous knowledge with this easy-to-follow course',
        mentor: 'Cristian Doru Barin',
        hours: '14 hours',
        lectures: '113',
        price: 134.99,
        img: 'https://img-a.udemycdn.com/course/240x135/1046722_cbd7_2.jpg',
    },
    {
        name: 'Complete Course Web Development',
        description: 'Become a full-stack web developer with just one course. HTML, CSS, Javascript, Node, React, MongoDB and more!',
        mentor: 'Jhankar Mahbub',
        hours: '80 hours',
        lectures: '570',
        price: 70.99,
        img: 'https://i.ytimg.com/vi/p0F-k3C1zns/maxresdefault.jpg',
    },
    {
        name: 'Design Thinking in 3 Steps',
        description: 'Understand your audience, envision a creative solution, and test your prototype',
        mentor: 'Alan Cooper',
        hours: '2 hours',
        lectures: '55',
        price: 34.99,
        img: 'https://img-a.udemycdn.com/course/240x135/1065056_41ed_5.jpg',
    },
    {
        name: 'Illustrator CC 2020 MasterClass',
        description: 'Master Adobe Illustrator CC with this in-depth training for all levels.',
        mentor: 'Martin Perhiniak',
        hours: '13 hours',
        lectures: '113',
        price: 104.99,
        img: 'https://img-a.udemycdn.com/course/240x135/1197206_7201_3.jpg',
    },
    {
        name: 'Graphic Design Masterclass - Learn GREAT Design',
        description: 'The Ultimate Graphic Design Course Which Covers Photoshop, Illustrator, InDesign,Design Theory, Branding and Logo Design',
        mentor: 'Lindsay Marsh',
        hours: '19 hours',
        lectures: '162',
        price: 79.99,
        img: 'https://i.ytimg.com/vi/8oisaiPASeo/hqdefault.jpg',
    },
    {
        name: 'The Complete Cyber Security Course : Hackers Exposed!',
        description: 'Volume 1 : Become a Cyber Security Specialist, Learn How to Stop Hackers, Prevent Hacking, Learn IT Security & INFOSEC',
        mentor: 'Nathan House',
        hours: '12 hours',
        lectures: '124',
        price: 119.99,
        img: 'https://img-a.udemycdn.com/course/240x135/614772_233b_9.jpg',
    },
    {
        name: 'Artificial Intelligence: Optimization Algorithms in Python',
        description: 'Learn how to build optimization algorithms from the ground up!',
        mentor: 'Kirill Eremenko',
        hours: '7 hours',
        lectures: '63',
        price: 199.99,
        img: 'https://couponos.me/wp-content/uploads/Artificial-Intelligence-Optimization-Algorithms-in-Python.jpg',
    },
    {
        name: 'Complete Course Web Development',
        description: 'Become a full-stack web developer with just one course. HTML, CSS, Javascript, Node, React, MongoDB and more!',
        mentor: 'Jhankar Mahbub',
        hours: '80 hours',
        lectures: '570',
        price: 70.99,
        img: 'https://i.ytimg.com/vi/p0F-k3C1zns/maxresdefault.jpg',
    },

];

export default courses;